// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vejwgliqovftbrbmonoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlandnbGlxb3ZmdGJyYm1vbm9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODIyODksImV4cCI6MjA2OTk1ODI4OX0.-2abUkhyHPKB-JtmhS5-hhPRutRMY87-eQdnV2mvPP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);